### ISSUE TITLE
Question about start time of preictal interval

### ISSUE THREAD

**Issue by ducnx** [SMorettini/CNNs-on-CHB-MIT#3]
Can you please explain why you subtract (30 + 3) minutes at the referenced line? I thought that with SOP = 30 min and SPH = 3 min, we only subtract 3 minutes from the start time of the seizure onset?
https://github.com/MesSem/CNNs-on-CHB-MIT/blob/e1e7a19ded971d521054fd3a063a7943f9c53336/DataserToSpectogram.py#L288

**Comment by SMorettini** [comment]
Following the paper, they defined preictal data the data acquired from 35 to 5 minutes before the ictal. But using these values some seizures will be excluded because they happen too near each other. So I decreased the 5 minutes to 3 to have the same numbers of seizures for patients like in the paper.
