### ISSUE TITLE
threshold

### ISSUE THREAD

**Issue by fateme94** [SMorettini/CNNs-on-CHB-MIT#5]
hi
Why don't consider all 13 patients?
and 
what are the threshold?

**Comment by SMorettini** [comment]
Hi,

> Why don't consider all 13 patients?

I didn't considered all patient because our objective was to follow the paper [Truong, Nhan Duy, et al. "Convolutional neural networks for seizure prediction using intracranial and scalp electroencephalogram." Neural Networks 105 (2018): 104-111.](https://www.sciencedirect.com/science/article/pii/S0893608018301485) and try to obtain similar results.

The problem was that the we weren't able to obtain the same amount data of some patients from the dataset. For example, in the paper, for some patients there was 8 hour of interictal but we found 14(numbers are only for example, there aren't real value). If the difference of the data we were able to found and the data they proposed was similar we considered the paper otherwise no.

**Comment by SMorettini** [comment]
> what are the threshold?

Could you explain better the question?

If I well understood what you are referring to, the thresholds are used to interpret the output of the CNN. The CNN gives as output a value from 0 to 1. The threshold needs to split the interval, for example:
```
# Invented variables, only for example
if(output_CNN>threshold):
      print("The data is PREICTAL")
else:
      print("The data is INTERICTAL")
```
